<?php
/**
 * Accordion, on background, 3 column, default
 */
return array(
	'title'      => __( 'Accordion, on background, 3 column, default', 'abpatterns' ),
	'categories' => array( 'accordions' ),
	'content'    => '<!-- wp:group {"align":"full","backgroundColor":"background-primary","paddingTop":13,"paddingBottom":13} -->
	<div class="wp-block-group alignfull has-background-primary-background-color has-background pt__13 pb__13"><!-- wp:ainoblocks/grid-container {"columnGap":"col-gap-m"} -->
	<div class="wp-block-ainoblocks-grid-container alignwide ab-grid-block col-gap-m"><!-- wp:ainoblocks/grid-item {"gridColumnStartDesktop":1,"gridColumnEndDesktop":5,"gridColumnStartTablet":1,"gridColumnEndTablet":13,"gridColumnStartMobile":1,"gridColumnEndMobile":13,"justifyItem":"stretch","paddingTop":5} -->
	<div class="wp-block-ainoblocks-grid-item col_start_d__1 col_end_d__5 col_start_t__1 col_end_t__13 col_start_m__1 col_end_m__13 align-self__start justify-self__stretch no-stacking pt__5"><!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What do you think is the best way to keep learning when you are running a business?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What do you think is the best way to keep learning when you are running a business?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Great question! My answer is there\'s no one right way to go about it. Even though today\'s fast-paced business world can demand optimised time management, self-accelerated education resources is critical for any entrepreneur looking to gain more knowledge on.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What is the best digital marketing strategy that you have used?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What is the best digital marketing strategy that you have used?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">We have used a diversified digital marketing strategy to grow our business including SEO, Social Media Marketing, PPC, Content Marketing, Email Marketing and even Mobile Marketing.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What\'s your favourite type of marketing?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What\'s your favourite type of marketing?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Marketing is the communication of your brand vision, mission and value through a variety of channels.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block --></div>
	<!-- /wp:ainoblocks/grid-item -->
	
	<!-- wp:ainoblocks/grid-item {"gridColumnStartDesktop":5,"gridColumnEndDesktop":9,"gridColumnStartTablet":1,"gridColumnEndTablet":13,"gridColumnStartMobile":1,"gridColumnEndMobile":13,"justifyItem":"stretch","paddingTop":5} -->
	<div class="wp-block-ainoblocks-grid-item col_start_d__5 col_end_d__9 col_start_t__1 col_end_t__13 col_start_m__1 col_end_m__13 align-self__start justify-self__stretch no-stacking pt__5"><!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What do you think is the best way to keep learning when you are running a business?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What do you think is the best way to keep learning when you are running a business?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Great question! My answer is there\'s no one right way to go about it. Even though today\'s fast-paced business world can demand optimised time management, self-accelerated education resources is critical for any entrepreneur looking to gain more knowledge on.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What is the best digital marketing strategy that you have used?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What is the best digital marketing strategy that you have used?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">We have used a diversified digital marketing strategy to grow our business including SEO, Social Media Marketing, PPC, Content Marketing, Email Marketing and even Mobile Marketing.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What\'s your favourite type of marketing?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What\'s your favourite type of marketing?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Marketing is the communication of your brand vision, mission and value through a variety of channels.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block --></div>
	<!-- /wp:ainoblocks/grid-item -->
	
	<!-- wp:ainoblocks/grid-item {"gridColumnStartDesktop":9,"gridColumnEndDesktop":13,"gridColumnStartTablet":1,"gridColumnEndTablet":13,"gridColumnStartMobile":1,"gridColumnEndMobile":13,"justifyItem":"stretch","paddingTop":5} -->
	<div class="wp-block-ainoblocks-grid-item col_start_d__9 col_end_d__13 col_start_t__1 col_end_t__13 col_start_m__1 col_end_m__13 align-self__start justify-self__stretch no-stacking pt__5"><!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What do you think is the best way to keep learning when you are running a business?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What do you think is the best way to keep learning when you are running a business?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Great question! My answer is there\'s no one right way to go about it. Even though today\'s fast-paced business world can demand optimised time management, self-accelerated education resources is critical for any entrepreneur looking to gain more knowledge on.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What is the best digital marketing strategy that you have used?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What is the best digital marketing strategy that you have used?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">We have used a diversified digital marketing strategy to grow our business including SEO, Social Media Marketing, PPC, Content Marketing, Email Marketing and even Mobile Marketing.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block -->
	
	<!-- wp:ainoblocks/accordion-faq-block {"backgroundColor":"background-secondary","borderRadius":"xs","iconPosition":"icon__left","question":"What\'s your favourite type of marketing?","style":{"border":{"width":"1px"}},"borderColor":"background-secondary","textColor":"font-primary","className":"br__xs","paddingTop":8,"paddingBottom":8,"paddingLeft":8,"paddingRight":8} -->
	<div class="wp-block-ainoblocks-accordion-faq-block icon__left br__xs has-border-color has-background-secondary-border-color has-font-primary-color has-background-secondary-background-color has-text-color has-background br-all__xs pt__8 pb__8 pl__8 pr__8" style="border-width:1px" x-data="{ open: false }" @click="open = !open" :class="{\'open\': open, \'close\': ! open }"><div class="accordion"><h3 class="has-xxs-font-size">What\'s your favourite type of marketing?</h3></div><div class="panel"><!-- wp:paragraph {"placeholder":"Write an answer ...","textColor":"font-secondary","fontSize":"text-xs","paddingTop":8} -->
	<p class="has-font-secondary-color has-text-color has-text-xs-font-size pt__8">Marketing is the communication of your brand vision, mission and value through a variety of channels.</p>
	<!-- /wp:paragraph --></div></div>
	<!-- /wp:ainoblocks/accordion-faq-block --></div>
	<!-- /wp:ainoblocks/grid-item --></div>
	<!-- /wp:ainoblocks/grid-container --></div>
	<!-- /wp:group -->',
);